### ISSUE TITLE
Github actions continuous integration permission denied 

### ISSUE THREAD

**Issue by GustavFriis** [lansoskar/ExamprojectBeSammen#23]
After trying to run Continuous Intergration its giving an error while trying to build the gradle, telling us that permission denied.

The workflow is under the main.yml file

**Comment by GustavFriis** [comment]
@Lakruzz kan du prøve at kigge på det? forstår ikke hvofor den siger permission denied

**Comment by lakruzz** [comment]
[gradlew](https://github.com/lansoskar/ExamprojectBeSammen/blob/master/gradlew) er et shell script som er blevet oprette dengang i valgte at jeres projekt skulle bygges med Gradle.

Men I har (måske?) gjort det på en Windows maksin og derfor er execute bit ikke blevet sat. Nu skal I bruge det på Linux (en container i GitHub Actions) og scriptet han ikke eksekveres, derfor får i fejlen.



**Løsning:**

I en bash shell (f.eks. i et GitHub CodeSpace)

``` shell
chmod +x gradlew
```
@GustavFriis
